# Generated by Django 3.2.7 on 2021-09-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('goal', models.TextField(null=True)),
                ('passs', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
